import Head from 'next/head';
import Header from '../components/header';
import Banner from '../components/banner';
import Counter from '../components/counter';
import About from '../components/about';
import Anatomy from '../components/anatomy';
import Faq from '../components/faq';
import Footer from '../components/footer';
import HeroRarity from '../components/hero-rarity';
import WhyAiza from '../components/why-aiza';
import BundlesInfo from '../components/bundle-info';
import Brand from '../components/brand';
import InoExchange from '../components/ino-exchange';
import Testimonial from '../components/testimonial';
import CollectionBrand from '../components/collection-brand';
import HeroChest from '../components/hero-chest';

export default function Home() {
  return (
    <>
      <Head>
        <title>Aiza World</title>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Header />
        <Banner />
        <Counter />
        <About />
        <Anatomy />
        <div className="wrap_bg">
          <HeroRarity />
          <WhyAiza />
          <BundlesInfo />
          <HeroChest />
        </div>

        <InoExchange />
        <div className="wrap_bg">
          <CollectionBrand />
          <Brand />
        </div>
        <Testimonial />
        <Faq />
        <Footer />
      </div>
    </>
  );
}
